# Format documented here
# http://www.mkdocs.org/user-guide/configuration/
# https://squidfunk.github.io/mkdocs-material/getting-started/

site_url: https://www.utplsql.org/
site_name: utPLSQL
remote_branch: mkdocs_site
remote_name: origin
site_description: utPLSQL Ultimate Testing Framework for Oracle PL/SQL
copyright: > 
  Copyright &copy; 2016 - 2026 utPLSQL Team
  <a href="#__consent">Change cookie settings</a>
extra_css:
  - assets/topbar.css
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  logo: assets/icon-transparent.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
extra:
  # sets scope of cookies to use a common path (root)
#  scope: "/"
  analytics:
    provider: google
    property: G-WMFVR98J0Q
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/utPLSQL/utPLSQL/discussions/new?category=documentation-feedback" target="_blank" rel="noopener noreferrer">GitHub Discussions</a>.
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/utPLSQL
    - icon: fontawesome/regular/comment
      link: https://github.com/utPLSQL/utPLSQL/discussions
    - icon: fontawesome/brands/github
      link: https://github.com/utPLSQL
    - icon: fontawesome/solid/envelope
      link: mailto:utPLSQL@utPLSQL.org
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    # the cookie: utplsql-consent allows for shred cookie across all documentation versions and the global site
    cookie: utplsql-consent
  version:            # disable for offline docs
    provider: mike    # disable for offline docs
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: true
use_directory_urls: false
#strict: true

plugins:
  - search
  - git-revision-date-localized: # disable for offline docs
      enable_creation_date: true # disable for offline docs
      type: datetime             # disable for offline docs
  - include-markdown
  - blog:
      blog_dir: announcements
      post_date_format: long        # e.g. "June 10, 2026"
      post_url_format: "{slug}"     # keeps URLs clean
      archive: false
      categories: true
nav:
  - Home: index.md
  - Announcements:
      - announcements/index.md
  - Documentation:
      - documentation.md
      - utPLSQL framework: utPLSQL/latest
      - utPLSQL-cli: utPLSQL-cli.md
      - utPLSQL-maven plugin: utPLSQL-maven-plugin.md
      - SQLDeveloper extension: utPLSQL-SQLDeveloper.md
      - PL/SQL Developer plugin: utPLSQL-PLSQL-Developer.md
  - Downloads: downloads.md
  - Resources: resources.md
  - About: about.md
  - Contributing: contributing.md
